### ISSUE TITLE
gpbo can not use

### ISSUE THREAD

**Issue by weidong8405347** [markm541374/gpbo#2]
when pip install git+https://github.com/markm541374/gpbo@master, it can not be installed successfully
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-nr05j6ca/setup.py", line 56, in <module>
        long_description=readme(),
      File "/tmp/pip-req-build-nr05j6ca/setup.py", line 10, in readme
        with open('gpbo/README.rst') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'gpbo/README.rst'

**Comment by markm541374** [comment]
This should now be fixed. The file was moved to README.md at some point.
